package com.feefasoft.a20230207_slavatsytsikov_nytschools.model;

public class SchoolDetails {

    public String dbn;
    public String school_name;
    public String boro;
    public String overview_paragraph;
    public String school_10th_seats;
    public String academicopportunities1;
    public String academicopportunities2;
    public String ell_programs;
    public String neighborhood;
    public String building_code;
    public String location;
    public String phone_number;
    public String fax_number;
    public String school_email;
    public String website;
    public String subway;
    public String bus;
    public String grades2018;
    public String finalgrades;
    public String total_students;
    public String extracurricular_activities;
    public String school_sports;
    public String attendance_rate;
    public String pct_stu_enough_variety;
    public String pct_stu_safe;
    public String school_accessibility_description;
    public String directions1;
    public String requirement1_1;
    public String requirement2_1;
    public String requirement3_1;
    public String requirement4_1;
    public String requirement5_1;
    public String offer_rate1;
    public String program1;
    public String code1;
    public String interest1;
    public String method1;
    public String seats9ge1;
    public String grade9gefilledflag1;
    public String grade9geapplicants1;
    public String seats9swd1;
    public String grade9swdfilledflag1;
    public String grade9swdapplicants1;
    public String seats101;
    public String admissionspriority11;
    public String admissionspriority21;
    public String admissionspriority31;
    public String grade9geapplicantsperseat1;
    public String grade9swdapplicantsperseat1;
    public String primary_address_line_1;
    public String city;
    public String zip;
    public String state_code;
    public String latitude;
    public String longitude;
    public String community_board;
    public String council_district;
    public String census_tract;
    public String bin;
    public String bbl;
    public String nta;
    public String borough;

}